staff
budatasci/budatasci.github.io pull request #1
Opened 2023-01-26 23:26 UTC by Yu-Yang-Wang

2023-01-27 01:08 UTC, budatasci requested changes
looks good so far, just added a couple of minor changes :)

2023-01-27 01:08 UTC, budatasci commented on _staffers/Andy Yang.md
> +Class Year: 2024
change to CDS 2024

2023-01-27 01:08 UTC, budatasci commented on _staffers/Christina Xu.md
> +Class Year: 2023
change to CAS 2023

2023-01-27 01:08 UTC, budatasci commented on _staffers/Christina Xu.md
> +I want to provide resources and support to data science and related majors that I wish I had
delete

2023-01-27 01:08 UTC, budatasci commented on _staffers/Kewen(Kolvin) Liu.md
> +Class Year: 2023
change to CAS 2023

2023-01-27 01:08 UTC, budatasci commented on _staffers/Kewen(Kolvin) Liu.md
> +Data science skills are very important in every aspect of work and life and I would love to help people who are interested in gaining such knowledge and skills despite their different backgrounds.
delete

2023-01-27 01:08 UTC, budatasci commented on _staffers/Lavya Midha.md
> +Class Year: 2025
change to CDS 2025

2023-01-27 01:08 UTC, budatasci commented on _staffers/Lavya Midha.md
> +Have always been really interested in coding and learning more about data science, this will be a way for me to not just learn about different concepts related to data science but also help other peo
delete

2023-01-27 01:08 UTC, budatasci commented on _staffers/Ryan Nie.md
> +Class Year: 2023
change to CAS 2023

2023-01-27 01:08 UTC, budatasci commented on _staffers/Ryan Nie.md
> +DS/ML offers new perspectives at explaining and finding patterns in the world, and being a part of this revolutionary field is very rewarding to me.
delete

2023-01-27 01:08 UTC, budatasci commented on _staffers/Serena Theobald.md
> +Class Year: 2025
change to CDS 2025

2023-01-27 01:08 UTC, budatasci commented on _staffers/Serena Theobald.md
> + I’d like to help provide data science undergrads with more resources by hosting coding workshops and datathons.
delete

2023-01-27 01:08 UTC, budatasci commented on _staffers/Valerie(Yuyang) Wang.md
> +Class Year: 2024
change to CAS 2024

2023-01-27 01:08 UTC, budatasci commented on _staffers/Valerie(Yuyang) Wang.md
> +I want to see more practical use of statistical knowledge.
delete

2023-01-27 01:08 UTC, budatasci commented on _staffers/Veer Sawhney.md
> +Class Year: 2023
change to CAS 2023

2023-01-27 01:08 UTC, budatasci commented on _staffers/Vy Nguyen.md
> +Class Year: 2024
change to CDS 2024

2023-01-27 01:08 UTC, budatasci commented on _staffers/Vy Nguyen.md
> + I want to deepen my data science knowledge and being surrounded by people who have similar interest as me
delete

2023-01-30 20:39 UTC, Yu-Yang-Wang commented
resolve all request

2023-02-03 01:53 UTC, merged